from app.db.database import SessionLocal, engine
from app import models
from sqlalchemy.orm import Session
from sqlalchemy.exc import OperationalError
from sqlalchemy import text
from passlib.context import CryptContext
import logging
import time

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

def wait_for_db(max_retries=30, delay=2):
    logger.info("Waiting for database connection...")
    for i in range(max_retries):
        try:
            # Try to create a session and run a simple query
            db = SessionLocal()
            db.execute(text("SELECT 1"))
            db.close()
            logger.info("Database is ready!")
            return
        except OperationalError:
            logger.warning(f"Database not ready yet. Retrying in {delay} seconds... ({i+1}/{max_retries})")
            time.sleep(delay)
        except Exception as e:
            logger.error(f"Unexpected error while waiting for DB: {e}")
            time.sleep(delay)
    
    raise Exception("Could not connect to the database after multiple retries.")

def seed_users(db: Session):
    """ Creates default Super Admin and Instructor users if they don't exist """
    
    # 1. Create Admin
    admin_email = "admin@scale.edu"
    if not db.query(models.User).filter(models.User.email == admin_email).first():
        admin_user = models.User(
            email=admin_email,
            hashed_password=pwd_context.hash("AdminPass123!"),
            role="admin",
            is_approved=True 
        )
        db.add(admin_user)
        logger.info(f"Created Super Admin: {admin_email}")

    # 2. Create Instructor
    inst_email = "instructor@scale.edu"
    if not db.query(models.User).filter(models.User.email == inst_email).first():
        inst_user = models.User(
            email=inst_email,
            hashed_password=pwd_context.hash("TeachPass123!"),
            role="instructor",
            is_approved=True
        )
        db.add(inst_user)
        logger.info(f"Created Default Instructor: {inst_email}")
    
    db.commit()

def generate_questions():
    """ Generates 200 questions across top 20 hack methods """
    
    # Categories: 
    # 1. SQLi, 2. XSS, 3. Phishing, 4. MitM, 5. DoS/DDoS, 
    # 6. Credential Stuffing, 7. CSRF, 8. SSRF, 9. Ransomware, 10. Buffer Overflow, 
    # 11. XXE, 12. Directory Traversal, 13. Insecure Deserialization, 14. Session Hijacking, 
    # 15. Command Injection, 16. Zero-Day, 17. DNS Spoofing, 18. Trojans, 19. Keylogging, 20. Priv Escalation
    
    questions = []

    # --- 1. SQL Injection (SQLi) ---
    questions.extend([
        {"text": "What does SQL stand for?", "type": "multiple_choice", "topic": "SQL Injection", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "Structured Query Language.", "options": [{"text": "Structured Query Language", "is_correct": True}, {"text": "Simple Query Logic", "is_correct": False}, {"text": "Standard Query Loop", "is_correct": False}, {"text": "System Question Language", "is_correct": False}]},
        {"text": "Which character is typically used to break an SQL query string?", "type": "multiple_choice", "topic": "SQL Injection", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "The single quote is often used to delimit strings in SQL.", "options": [{"text": "' (Single Quote)", "is_correct": True}, {"text": "@ (At symbol)", "is_correct": False}, {"text": "^ (Caret)", "is_correct": False}, {"text": "~ (Tilde)", "is_correct": False}]},
        {"text": "What is the primary defense against SQL Injection?", "type": "multiple_choice", "topic": "SQL Injection", "difficulty": "Medium", "skill_focus": "Defense", "explanation": "Prepared statements separate code from data.", "options": [{"text": "Prepared Statements / Parameterized Queries", "is_correct": True}, {"text": "Input Hashing", "is_correct": False}, {"text": "Firewalls", "is_correct": False}, {"text": "HTTPS", "is_correct": False}]},
        {"text": "Which condition is commonly used in SQLi to dump data (e.g., OR 1=...)?", "type": "multiple_choice", "topic": "SQL Injection", "difficulty": "Easy", "skill_focus": "Exploitation", "explanation": "1=1 is a tautology (always true).", "options": [{"text": "1=1", "is_correct": True}, {"text": "1=0", "is_correct": False}, {"text": "0=1", "is_correct": False}, {"text": "Null=Null", "is_correct": False}]},
        {"text": "What type of SQLi relies on true/false server responses rather than returning data directly?", "type": "multiple_choice", "topic": "SQL Injection", "difficulty": "Hard", "skill_focus": "Knowledge", "explanation": "Blind SQLi infers data based on application behavior.", "options": [{"text": "Blind SQL Injection", "is_correct": True}, {"text": "Union-Based SQLi", "is_correct": False}, {"text": "Error-Based SQLi", "is_correct": False}, {"text": "Direct SQLi", "is_correct": False}]},
        {"text": "Which SQL statement is used to combine results from two queries, often used in attacks?", "type": "multiple_choice", "topic": "SQL Injection", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "UNION allows an attacker to append results to the original query.", "options": [{"text": "UNION", "is_correct": True}, {"text": "JOIN", "is_correct": False}, {"text": "MERGE", "is_correct": False}, {"text": "LINK", "is_correct": False}]},
        {"text": "If an attack successfully drops a table, what principle was violated?", "type": "multiple_choice", "topic": "SQL Injection", "difficulty": "Medium", "skill_focus": "Defense", "explanation": "The database user had excessive privileges (Principle of Least Privilege).", "options": [{"text": "Least Privilege", "is_correct": True}, {"text": "Defense in Depth", "is_correct": False}, {"text": "Security by Obscurity", "is_correct": False}, {"text": "Open Design", "is_correct": False}]},
        {"text": "What tool is commonly used to automate SQL Injection detection?", "type": "multiple_choice", "topic": "SQL Injection", "difficulty": "Medium", "skill_focus": "Tools", "explanation": "SQLMap is the standard open-source tool for this.", "options": [{"text": "SQLMap", "is_correct": True}, {"text": "Nmap", "is_correct": False}, {"text": "Wireshark", "is_correct": False}, {"text": "John the Ripper", "is_correct": False}]},
        {"text": "Which database is associated with the 'information_schema' table?", "type": "multiple_choice", "topic": "SQL Injection", "difficulty": "Hard", "skill_focus": "Knowledge", "explanation": "MySQL, PostgreSQL, and SQL Server use information_schema to store metadata.", "options": [{"text": "MySQL", "is_correct": True}, {"text": "MongoDB", "is_correct": False}, {"text": "Redis", "is_correct": False}, {"text": "Cassandra", "is_correct": False}]},
        {"text": "Does using a stored procedure guarantee safety from SQLi?", "type": "multiple_choice", "topic": "SQL Injection", "difficulty": "Hard", "skill_focus": "Defense", "explanation": "Not if the stored procedure itself constructs dynamic SQL via string concatenation.", "options": [{"text": "No, if dynamic SQL is used inside it", "is_correct": True}, {"text": "Yes, always", "is_correct": False}, {"text": "Only in Oracle", "is_correct": False}, {"text": "Only in SQL Server", "is_correct": False}]},
    ])

    # --- 2. Cross-Site Scripting (XSS) ---
    questions.extend([
        {"text": "What does XSS stand for?", "type": "multiple_choice", "topic": "XSS", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "Cross-Site Scripting.", "options": [{"text": "Cross-Site Scripting", "is_correct": True}, {"text": "Extra Secure Socket", "is_correct": False}, {"text": "Extreme Server Script", "is_correct": False}, {"text": "XML Site Sheet", "is_correct": False}]},
        {"text": "Which XSS type involves the malicious script being saved on the server's database?", "type": "multiple_choice", "topic": "XSS", "difficulty": "Medium", "skill_focus": "Knowledge", "explanation": "Stored (Persistent) XSS saves the payload to the database.", "options": [{"text": "Stored XSS", "is_correct": True}, {"text": "Reflected XSS", "is_correct": False}, {"text": "DOM XSS", "is_correct": False}, {"text": "Server XSS", "is_correct": False}]},
        {"text": "What is the primary scripting language used in XSS attacks?", "type": "multiple_choice", "topic": "XSS", "difficulty": "Easy", "skill_focus": "Exploitation", "explanation": "JavaScript is the language of the web browser.", "options": [{"text": "JavaScript", "is_correct": True}, {"text": "Python", "is_correct": False}, {"text": "C++", "is_correct": False}, {"text": "Java", "is_correct": False}]},
        {"text": "What HTML tag is most commonly used to inject XSS?", "type": "multiple_choice", "topic": "XSS", "difficulty": "Easy", "skill_focus": "Exploitation", "explanation": "The script tag is the standard way to execute JS.", "options": [{"text": "<script>", "is_correct": True}, {"text": "<body>", "is_correct": False}, {"text": "<head>", "is_correct": False}, {"text": "<table>", "is_correct": False}]},
        {"text": "What is the best defense against XSS when rendering user input?", "type": "multiple_choice", "topic": "XSS", "difficulty": "Medium", "skill_focus": "Defense", "explanation": "Context-aware output encoding prevents the browser from interpreting data as code.", "options": [{"text": "Output Encoding/Escaping", "is_correct": True}, {"text": "Input Validation only", "is_correct": False}, {"text": "Using HTTP only", "is_correct": False}, {"text": "Disabling Cookies", "is_correct": False}]},
        {"text": "What HTTP header helps mitigate XSS risks?", "type": "multiple_choice", "topic": "XSS", "difficulty": "Hard", "skill_focus": "Defense", "explanation": "Content Security Policy (CSP) restricts sources of executable scripts.", "options": [{"text": "Content-Security-Policy (CSP)", "is_correct": True}, {"text": "X-Frame-Options", "is_correct": False}, {"text": "Strict-Transport-Security", "is_correct": False}, {"text": "Access-Control-Allow-Origin", "is_correct": False}]},
        {"text": "Which flag prevents JavaScript from accessing a cookie?", "type": "multiple_choice", "topic": "XSS", "difficulty": "Medium", "skill_focus": "Defense", "explanation": "HttpOnly cookies cannot be read by `document.cookie`.", "options": [{"text": "HttpOnly", "is_correct": True}, {"text": "Secure", "is_correct": False}, {"text": "SameSite", "is_correct": False}, {"text": "Domain", "is_correct": False}]},
        {"text": "What is DOM-based XSS?", "type": "multiple_choice", "topic": "XSS", "difficulty": "Hard", "skill_focus": "Knowledge", "explanation": "The vulnerability exists in client-side code rather than server-side code.", "options": [{"text": "Attack executed entirely in the browser DOM", "is_correct": True}, {"text": "Attack on the Database Object Model", "is_correct": False}, {"text": "Attack via Email", "is_correct": False}, {"text": "Attack on server logs", "is_correct": False}]},
        {"text": "Which function in JavaScript is dangerous and often leads to XSS/Code Injection?", "type": "multiple_choice", "topic": "XSS", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "eval() executes a string as code.", "options": [{"text": "eval()", "is_correct": True}, {"text": "alert()", "is_correct": False}, {"text": "console.log()", "is_correct": False}, {"text": "parseInt()", "is_correct": False}]},
        {"text": "If a user clicks a link in an email and is exploited via XSS, what type is it likely?", "type": "multiple_choice", "topic": "XSS", "difficulty": "Medium", "skill_focus": "Knowledge", "explanation": "Reflected XSS bounces the payload off the server immediately via the URL.", "options": [{"text": "Reflected XSS", "is_correct": True}, {"text": "Stored XSS", "is_correct": False}, {"text": "Local XSS", "is_correct": False}, {"text": "Passive XSS", "is_correct": False}]},
    ])

    # --- 3. Phishing ---
    questions.extend([
        {"text": "What is Phishing?", "type": "multiple_choice", "topic": "Phishing", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "Social engineering using fraudulent messages.", "options": [{"text": "Deceptive emails to steal data", "is_correct": True}, {"text": "Catching fish", "is_correct": False}, {"text": "Scanning ports", "is_correct": False}, {"text": "Decrypting passwords", "is_correct": False}]},
        {"text": "What is 'Spear Phishing'?", "type": "multiple_choice", "topic": "Phishing", "difficulty": "Medium", "skill_focus": "Knowledge", "explanation": "Spear phishing targets specific individuals or organizations.", "options": [{"text": "Targeted attack on a specific person", "is_correct": True}, {"text": "Random spam emails", "is_correct": False}, {"text": "Voice phishing", "is_correct": False}, {"text": "SMS phishing", "is_correct": False}]},
        {"text": "What is 'Whaling' in the context of phishing?", "type": "multiple_choice", "topic": "Phishing", "difficulty": "Medium", "skill_focus": "Knowledge", "explanation": "Whaling targets high-profile executives (CEOs, CFOs).", "options": [{"text": "Targeting high-level executives", "is_correct": True}, {"text": "Targeting large databases", "is_correct": False}, {"text": "Targeting system admins only", "is_correct": False}, {"text": "Phishing via underwater cables", "is_correct": False}]},
        {"text": "What is 'Smishing'?", "type": "multiple_choice", "topic": "Phishing", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "Phishing via SMS text messages.", "options": [{"text": "Phishing via SMS/Text", "is_correct": True}, {"text": "Small Phishing", "is_correct": False}, {"text": "Smart Phishing", "is_correct": False}, {"text": "Social Media Phishing", "is_correct": False}]},
        {"text": "What is a Homograph attack in phishing?", "type": "multiple_choice", "topic": "Phishing", "difficulty": "Hard", "skill_focus": "Exploitation", "explanation": "Using look-alike characters (e.g., Cyrillic 'a' vs Latin 'a') to spoof URLs.", "options": [{"text": "Using look-alike characters in URLs", "is_correct": True}, {"text": "Sending home graphics", "is_correct": False}, {"text": "Attacking home routers", "is_correct": False}, {"text": "Using same-colored fonts", "is_correct": False}]},
        {"text": "What common psychological trigger does phishing rely on?", "type": "multiple_choice", "topic": "Phishing", "difficulty": "Easy", "skill_focus": "Psychology", "explanation": "Urgency (e.g., 'Account locked!') forces quick, unthinking errors.", "options": [{"text": "Urgency/Fear", "is_correct": True}, {"text": "Logic", "is_correct": False}, {"text": "Patience", "is_correct": False}, {"text": "Generosity", "is_correct": False}]},
        {"text": "What does 'Vishing' stand for?", "type": "multiple_choice", "topic": "Phishing", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "Voice Phishing (phone calls).", "options": [{"text": "Voice Phishing", "is_correct": True}, {"text": "Video Phishing", "is_correct": False}, {"text": "Virtual Phishing", "is_correct": False}, {"text": "Visual Phishing", "is_correct": False}]},
        {"text": "How can you verify a link destination before clicking?", "type": "multiple_choice", "topic": "Phishing", "difficulty": "Easy", "skill_focus": "Defense", "explanation": "Hovering over the link shows the actual URL.", "options": [{"text": "Hover over the link", "is_correct": True}, {"text": "Click it quickly", "is_correct": False}, {"text": "Reply to the email", "is_correct": False}, {"text": "Copy paste into Notepad", "is_correct": False}]},
        {"text": "What mechanism authenticates email senders to prevent spoofing?", "type": "multiple_choice", "topic": "Phishing", "difficulty": "Hard", "skill_focus": "Defense", "explanation": "SPF, DKIM, and DMARC are email auth protocols.", "options": [{"text": "SPF/DKIM/DMARC", "is_correct": True}, {"text": "SSL/TLS", "is_correct": False}, {"text": "SSH", "is_correct": False}, {"text": "HTTP", "is_correct": False}]},
        {"text": "A phishing email asking you to check an invoice usually contains what?", "type": "multiple_choice", "topic": "Phishing", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "Malicious attachments (PDF/Office docs with macros) are common.", "options": [{"text": "Malicious Attachment", "is_correct": True}, {"text": "A secure token", "is_correct": False}, {"text": "A valid receipt", "is_correct": False}, {"text": "Encrypted text", "is_correct": False}]},
    ])

    # --- 4. Man-in-the-Middle (MitM) ---
    questions.extend([
        {"text": "What is a Man-in-the-Middle attack?", "type": "multiple_choice", "topic": "MitM", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "Attacker intercepts communication between two parties.", "options": [{"text": "Intercepting data between two parties", "is_correct": True}, {"text": "Attacking the middle server", "is_correct": False}, {"text": "Sitting in the middle of a room", "is_correct": False}, {"text": "Stopping data flow", "is_correct": False}]},
        {"text": "What protocol effectively prevents MitM by encrypting traffic?", "type": "multiple_choice", "topic": "MitM", "difficulty": "Easy", "skill_focus": "Defense", "explanation": "HTTPS (via TLS/SSL) encrypts the channel.", "options": [{"text": "HTTPS (TLS/SSL)", "is_correct": True}, {"text": "HTTP", "is_correct": False}, {"text": "FTP", "is_correct": False}, {"text": "Telnet", "is_correct": False}]},
        {"text": "What is ARP Spoofing?", "type": "multiple_choice", "topic": "MitM", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "Linking the attacker's MAC address to a legitimate IP on a LAN.", "options": [{"text": "Faking MAC addresses on a LAN", "is_correct": True}, {"text": "Spoofing DNS records", "is_correct": False}, {"text": "Faking IP addresses on WAN", "is_correct": False}, {"text": "Spoofing email headers", "is_correct": False}]},
        {"text": "What is 'SSL Stripping'?", "type": "multiple_choice", "topic": "MitM", "difficulty": "Hard", "skill_focus": "Exploitation", "explanation": "Downgrading a connection from HTTPS to HTTP.", "options": [{"text": "Downgrading HTTPS to HTTP", "is_correct": True}, {"text": "Removing SSL certificates", "is_correct": False}, {"text": "Stealing SSL keys physically", "is_correct": False}, {"text": "Breaking SSL encryption math", "is_correct": False}]},
        {"text": "What tool is famous for Wi-Fi MitM attacks (Pineapple)?", "type": "multiple_choice", "topic": "MitM", "difficulty": "Medium", "skill_focus": "Tools", "explanation": "The WiFi Pineapple is a hardware tool for rogue APs.", "options": [{"text": "WiFi Pineapple", "is_correct": True}, {"text": "WiFi Banana", "is_correct": False}, {"text": "WiFi Apple", "is_correct": False}, {"text": "WiFi Orange", "is_correct": False}]},
        {"text": "What is a Rogue Access Point?", "type": "multiple_choice", "topic": "MitM", "difficulty": "Easy", "skill_focus": "Exploitation", "explanation": "An unauthorized Wi-Fi point set up to intercept traffic.", "options": [{"text": "Unauthorized Wi-Fi access point", "is_correct": True}, {"text": "A broken router", "is_correct": False}, {"text": "A hidden server", "is_correct": False}, {"text": "A restricted website", "is_correct": False}]},
        {"text": "What is Session Hijacking often a result of?", "type": "multiple_choice", "topic": "MitM", "difficulty": "Medium", "skill_focus": "Knowledge", "explanation": "If a session cookie is sent over unencrypted HTTP, MitM can steal it.", "options": [{"text": "Unencrypted Session Cookies", "is_correct": True}, {"text": "Strong passwords", "is_correct": False}, {"text": "Two-factor authentication", "is_correct": False}, {"text": "Encrypted hard drives", "is_correct": False}]},
        {"text": "What is DNS Spoofing?", "type": "multiple_choice", "topic": "MitM", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "Redirecting a domain name to a malicious IP address.", "options": [{"text": "Redirecting domain names to wrong IPs", "is_correct": True}, {"text": "Deleting domain names", "is_correct": False}, {"text": "Buying domain names", "is_correct": False}, {"text": "Encrypting DNS queries", "is_correct": False}]},
        {"text": "Which network layer does ARP Spoofing operate on?", "type": "multiple_choice", "topic": "MitM", "difficulty": "Hard", "skill_focus": "Knowledge", "explanation": "Layer 2 (Data Link Layer) uses MAC addresses.", "options": [{"text": "Layer 2 (Data Link)", "is_correct": True}, {"text": "Layer 3 (Network)", "is_correct": False}, {"text": "Layer 7 (Application)", "is_correct": False}, {"text": "Layer 1 (Physical)", "is_correct": False}]},
        {"text": "What prevents ARP Spoofing on enterprise switches?", "type": "multiple_choice", "topic": "MitM", "difficulty": "Hard", "skill_focus": "Defense", "explanation": "Dynamic ARP Inspection (DAI) validates ARP packets.", "options": [{"text": "Dynamic ARP Inspection", "is_correct": True}, {"text": "Port Security", "is_correct": False}, {"text": "Firewall", "is_correct": False}, {"text": "VLANs", "is_correct": False}]},
    ])

    # --- 5. DoS / DDoS ---
    questions.extend([
        {"text": "What is the difference between DoS and DDoS?", "type": "multiple_choice", "topic": "DoS/DDoS", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "DDoS uses multiple distributed sources (botnet).", "options": [{"text": "DDoS uses multiple attack sources", "is_correct": True}, {"text": "DoS is faster", "is_correct": False}, {"text": "DDoS is only for banks", "is_correct": False}, {"text": "They are the same", "is_correct": False}]},
        {"text": "What does a SYN Flood attack exploit?", "type": "multiple_choice", "topic": "DoS/DDoS", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "It exploits the TCP 3-way handshake by leaving connections half-open.", "options": [{"text": "TCP 3-way Handshake", "is_correct": True}, {"text": "UDP protocols", "is_correct": False}, {"text": "HTTP headers", "is_correct": False}, {"text": "DNS queries", "is_correct": False}]},
        {"text": "What is a Botnet?", "type": "multiple_choice", "topic": "DoS/DDoS", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "A network of compromised computers controlled by an attacker.", "options": [{"text": "Network of compromised computers", "is_correct": True}, {"text": "A robot network for cleaning", "is_correct": False}, {"text": "A fast internet connection", "is_correct": False}, {"text": "A firewall software", "is_correct": False}]},
        {"text": "What is a 'Slowloris' attack?", "type": "multiple_choice", "topic": "DoS/DDoS", "difficulty": "Hard", "skill_focus": "Exploitation", "explanation": "It keeps many connections open by sending HTTP headers very slowly.", "options": [{"text": "Low-bandwidth attack keeping connections open", "is_correct": True}, {"text": "High-bandwidth volume attack", "is_correct": False}, {"text": "Malware attack", "is_correct": False}, {"text": "Phishing attack", "is_correct": False}]},
        {"text": "What is an Amplification Attack?", "type": "multiple_choice", "topic": "DoS/DDoS", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "Sending a small request that generates a large response (e.g., NTP/DNS).", "options": [{"text": "Small request causes large response", "is_correct": True}, {"text": "Making the virus louder", "is_correct": False}, {"text": "Increasing wifi signal", "is_correct": False}, {"text": "Stealing more data", "is_correct": False}]},
        {"text": "What is the 'Ping of Death'?", "type": "multiple_choice", "topic": "DoS/DDoS", "difficulty": "Medium", "skill_focus": "History", "explanation": "Sending malformed or oversized ping packets to crash a system.", "options": [{"text": "Malformed/Oversized ICMP packet", "is_correct": True}, {"text": "Too many pings", "is_correct": False}, {"text": "Pinging a dead server", "is_correct": False}, {"text": "A sound effect", "is_correct": False}]},
        {"text": "What service helps mitigate DDoS attacks?", "type": "multiple_choice", "topic": "DoS/DDoS", "difficulty": "Medium", "skill_focus": "Defense", "explanation": "Cloudflare (and similar CDNs) absorb traffic.", "options": [{"text": "CDN / Traffic Scrubbing (e.g., Cloudflare)", "is_correct": True}, {"text": "Antivirus", "is_correct": False}, {"text": "Password Manager", "is_correct": False}, {"text": "Disk Encryption", "is_correct": False}]},
        {"text": "What is a LOIC (Low Orbit Ion Cannon)?", "type": "multiple_choice", "topic": "DoS/DDoS", "difficulty": "Medium", "skill_focus": "Tools", "explanation": "A popular open-source network stress testing / DDoS tool.", "options": [{"text": "DDoS Tool", "is_correct": True}, {"text": "Space weapon", "is_correct": False}, {"text": "Satellite internet", "is_correct": False}, {"text": "Firewall brand", "is_correct": False}]},
        {"text": "What is the goal of a Ransom DDoS (RDoS)?", "type": "multiple_choice", "topic": "DoS/DDoS", "difficulty": "Easy", "skill_focus": "Motivation", "explanation": "Extortion: threatening DDoS unless money is paid.", "options": [{"text": "Extortion / Money", "is_correct": True}, {"text": "Stealing passwords", "is_correct": False}, {"text": "Spying", "is_correct": False}, {"text": "Testing speed", "is_correct": False}]},
        {"text": "Does a DDoS attack usually involve stealing data?", "type": "multiple_choice", "topic": "DoS/DDoS", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "No, it targets Availability, not Confidentiality.", "options": [{"text": "No, it targets Availability", "is_correct": True}, {"text": "Yes, always", "is_correct": False}, {"text": "Yes, primarily", "is_correct": False}, {"text": "It depends on the weather", "is_correct": False}]},
    ])

    # --- 6. Brute Force / Credential Stuffing ---
    questions.extend([
        {"text": "What is Credential Stuffing?", "type": "multiple_choice", "topic": "Credential Stuffing", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "Using leaked username/password pairs on other sites.", "options": [{"text": "Using leaked credentials on other sites", "is_correct": True}, {"text": "Guessing random passwords", "is_correct": False}, {"text": "Stealing cookies", "is_correct": False}, {"text": "Creating fake accounts", "is_correct": False}]},
        {"text": "What is a Dictionary Attack?", "type": "multiple_choice", "topic": "Brute Force", "difficulty": "Easy", "skill_focus": "Exploitation", "explanation": "Using a list of common words/passwords.", "options": [{"text": "Using a wordlist of common passwords", "is_correct": True}, {"text": "Trying every combination (A-Z, 0-9)", "is_correct": False}, {"text": "Looking up words in a book", "is_correct": False}, {"text": "Attacking the dictionary file", "is_correct": False}]},
        {"text": "What is a Hybrid Attack?", "type": "multiple_choice", "topic": "Brute Force", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "Combining dictionary words with number/symbol variations.", "options": [{"text": "Dictionary words + variations", "is_correct": True}, {"text": "Physical and Digital attack", "is_correct": False}, {"text": "Windows and Linux attack", "is_correct": False}, {"text": "Fast and Slow attack", "is_correct": False}]},
        {"text": "What effectively stops simple Brute Force attacks?", "type": "multiple_choice", "topic": "Brute Force", "difficulty": "Easy", "skill_focus": "Defense", "explanation": "Account lockout after N failed attempts.", "options": [{"text": "Account Lockout Policies", "is_correct": True}, {"text": "Shorter passwords", "is_correct": False}, {"text": "Changing usernames", "is_correct": False}, {"text": "Hiding the login page", "is_correct": False}]},
        {"text": "What is the most effective defense against Credential Stuffing?", "type": "multiple_choice", "topic": "Credential Stuffing", "difficulty": "Medium", "skill_focus": "Defense", "explanation": "MFA prevents login even if the password is known.", "options": [{"text": "Multi-Factor Authentication (MFA)", "is_correct": True}, {"text": "Complex passwords", "is_correct": False}, {"text": "Antivirus", "is_correct": False}, {"text": "Firewall", "is_correct": False}]},
        {"text": "What file is commonly used as a wordlist (rockyou)?", "type": "multiple_choice", "topic": "Brute Force", "difficulty": "Medium", "skill_focus": "Tools", "explanation": "rockyou.txt is a famous leaked password list.", "options": [{"text": "rockyou.txt", "is_correct": True}, {"text": "passwords.doc", "is_correct": False}, {"text": "hack.exe", "is_correct": False}, {"text": "list.pdf", "is_correct": False}]},
        {"text": "What is 'Password Spraying'?", "type": "multiple_choice", "topic": "Brute Force", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "Trying one common password against MANY accounts to avoid lockout.", "options": [{"text": "One password against many accounts", "is_correct": True}, {"text": "Many passwords against one account", "is_correct": False}, {"text": "Emailing passwords", "is_correct": False}, {"text": "Resetting passwords", "is_correct": False}]},
        {"text": "What makes a Rainbow Table attack faster than Brute Force?", "type": "multiple_choice", "topic": "Brute Force", "difficulty": "Hard", "skill_focus": "Theory", "explanation": "It uses precomputed hash chains to reverse hashes.", "options": [{"text": "Precomputed hash chains", "is_correct": True}, {"text": "Better GPU", "is_correct": False}, {"text": "Faster internet", "is_correct": False}, {"text": "More computers", "is_correct": False}]},
        {"text": "What mitigates Rainbow Table attacks?", "type": "multiple_choice", "topic": "Brute Force", "difficulty": "Medium", "skill_focus": "Defense", "explanation": "Salting adds random data to the hash, invalidating precomputed tables.", "options": [{"text": "Salting passwords", "is_correct": True}, {"text": "Hashing twice", "is_correct": False}, {"text": "Using MD5", "is_correct": False}, {"text": "Keeping database offline", "is_correct": False}]},
        {"text": "Why is 'admin' / 'admin' a bad credential pair?", "type": "multiple_choice", "topic": "Brute Force", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "It is the default for many devices and the first thing guessed.", "options": [{"text": "Default / Easily guessed", "is_correct": True}, {"text": "Hard to remember", "is_correct": False}, {"text": "Too long", "is_correct": False}, {"text": "Cannot be typed", "is_correct": False}]},
    ])

    # --- 7. CSRF ---
    questions.extend([
        {"text": "What does CSRF stand for?", "type": "multiple_choice", "topic": "CSRF", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "Cross-Site Request Forgery.", "options": [{"text": "Cross-Site Request Forgery", "is_correct": True}, {"text": "Common Server Request Fail", "is_correct": False}, {"text": "Client Side Router Fix", "is_correct": False}, {"text": "Cross System Root File", "is_correct": False}]},
        {"text": "What does a CSRF attack achieve?", "type": "multiple_choice", "topic": "CSRF", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "Forces an authenticated user to perform an unwanted action.", "options": [{"text": "Forces user to perform unwanted action", "is_correct": True}, {"text": "Steals user password", "is_correct": False}, {"text": "Crashes the server", "is_correct": False}, {"text": "Intercepts Wi-Fi", "is_correct": False}]},
        {"text": "What is the standard defense against CSRF?", "type": "multiple_choice", "topic": "CSRF", "difficulty": "Medium", "skill_focus": "Defense", "explanation": "Anti-CSRF Tokens (Synchronizer Token Pattern).", "options": [{"text": "Anti-CSRF Tokens", "is_correct": True}, {"text": "Encryption", "is_correct": False}, {"text": "Complex Passwords", "is_correct": False}, {"text": "Hiding URLs", "is_correct": False}]},
        {"text": "Which cookie attribute helps prevent CSRF?", "type": "multiple_choice", "topic": "CSRF", "difficulty": "Medium", "skill_focus": "Defense", "explanation": "SameSite=Strict/Lax prevents sending cookies on cross-site requests.", "options": [{"text": "SameSite", "is_correct": True}, {"text": "HttpOnly", "is_correct": False}, {"text": "Secure", "is_correct": False}, {"text": "Expires", "is_correct": False}]},
        {"text": "Does CSRF work if the user is NOT logged in?", "type": "multiple_choice", "topic": "CSRF", "difficulty": "Easy", "skill_focus": "Theory", "explanation": "No, it relies on the user's active session.", "options": [{"text": "No", "is_correct": True}, {"text": "Yes", "is_correct": False}, {"text": "Only on mobile", "is_correct": False}, {"text": "Only on Wi-Fi", "is_correct": False}]},
        {"text": "Is reading data usually possible with standard CSRF?", "type": "multiple_choice", "topic": "CSRF", "difficulty": "Hard", "skill_focus": "Theory", "explanation": "No, CSRF is 'blind'. It sends state-changing requests but attacker can't see response (usually).", "options": [{"text": "No, it's a state-changing attack", "is_correct": True}, {"text": "Yes, always", "is_correct": False}, {"text": "Only JSON data", "is_correct": False}, {"text": "Only Images", "is_correct": False}]},
        {"text": "Which HTTP method is most dangerous for CSRF if misconfigured?", "type": "multiple_choice", "topic": "CSRF", "difficulty": "Medium", "skill_focus": "Theory", "explanation": "GET requests should not change state; if they do, CSRF is trivial (via image tags).", "options": [{"text": "GET (if used for state changes)", "is_correct": True}, {"text": "OPTIONS", "is_correct": False}, {"text": "HEAD", "is_correct": False}, {"text": "TRACE", "is_correct": False}]},
        {"text": "What is 'Login CSRF'?", "type": "multiple_choice", "topic": "CSRF", "difficulty": "Hard", "skill_focus": "Exploitation", "explanation": "Logging a victim into the attacker's account to track their activity.", "options": [{"text": "Logging victim into attacker's account", "is_correct": True}, {"text": "Stealing login credentials", "is_correct": False}, {"text": "Deleting login page", "is_correct": False}, {"text": "Brute forcing login", "is_correct": False}]},
        {"text": "Why doesn't the Same Origin Policy (SOP) stop CSRF?", "type": "multiple_choice", "topic": "CSRF", "difficulty": "Hard", "skill_focus": "Theory", "explanation": "SOP prevents reading responses, not sending requests.", "options": [{"text": "SOP prevents reading, not sending", "is_correct": True}, {"text": "SOP is deprecated", "is_correct": False}, {"text": "CSRF bypasses SOP automatically", "is_correct": False}, {"text": "SOP only works for images", "is_correct": False}]},
        {"text": "Can CAPTCHA prevent CSRF?", "type": "multiple_choice", "topic": "CSRF", "difficulty": "Medium", "skill_focus": "Defense", "explanation": "Yes, because the attacker cannot solve the CAPTCHA programmatically.", "options": [{"text": "Yes", "is_correct": True}, {"text": "No", "is_correct": False}, {"text": "Only google captcha", "is_correct": False}, {"text": "Only on Tuesdays", "is_correct": False}]},
    ])

    # --- 8. SSRF ---
    questions.extend([
        {"text": "What does SSRF stand for?", "type": "multiple_choice", "topic": "SSRF", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "Server-Side Request Forgery.", "options": [{"text": "Server-Side Request Forgery", "is_correct": True}, {"text": "Secure Socket Remote File", "is_correct": False}, {"text": "System Side Root Fix", "is_correct": False}, {"text": "Site Security Request Form", "is_correct": False}]},
        {"text": "Who performs the request in an SSRF attack?", "type": "multiple_choice", "topic": "SSRF", "difficulty": "Easy", "skill_focus": "Theory", "explanation": "The vulnerable server makes the request.", "options": [{"text": "The Web Server", "is_correct": True}, {"text": "The User's Browser", "is_correct": False}, {"text": "The Hacker's Laptop directly", "is_correct": False}, {"text": "The ISP", "is_correct": False}]},
        {"text": "What is a common target for SSRF in cloud environments?", "type": "multiple_choice", "topic": "SSRF", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "Instance Metadata Services (e.g., 169.254.169.254) contain keys.", "options": [{"text": "Metadata Services (169.254.169.254)", "is_correct": True}, {"text": "YouTube", "is_correct": False}, {"text": "Facebook", "is_correct": False}, {"text": "Public DNS", "is_correct": False}]},
        {"text": "Can SSRF be used to scan internal networks?", "type": "multiple_choice", "topic": "SSRF", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "Yes, the server can reach internal IPs that the outsider cannot.", "options": [{"text": "Yes, port scanning internal IPs", "is_correct": True}, {"text": "No, firewalls stop it", "is_correct": False}, {"text": "Only external IPs", "is_correct": False}, {"text": "Only if using FTP", "is_correct": False}]},
        {"text": "What URL scheme is often used in SSRF to read local files?", "type": "multiple_choice", "topic": "SSRF", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "file:///etc/passwd", "options": [{"text": "file://", "is_correct": True}, {"text": "http://", "is_correct": False}, {"text": "mailto:", "is_correct": False}, {"text": "tel:", "is_correct": False}]},
        {"text": "What is Blind SSRF?", "type": "multiple_choice", "topic": "SSRF", "difficulty": "Hard", "skill_focus": "Theory", "explanation": "The attacker doesn't see the response, but can observe timing or side effects.", "options": [{"text": "No response returned to attacker", "is_correct": True}, {"text": "Attacker is blindfolded", "is_correct": False}, {"text": "Server is offline", "is_correct": False}, {"text": "Full data is returned", "is_correct": False}]},
        {"text": "How do you mitigate SSRF?", "type": "multiple_choice", "topic": "SSRF", "difficulty": "Medium", "skill_focus": "Defense", "explanation": "Allowlisting domains and validating user input.", "options": [{"text": "Input Validation & Allowlisting", "is_correct": True}, {"text": "Disabling JS", "is_correct": False}, {"text": "Using HTTPS", "is_correct": False}, {"text": "Using Cookies", "is_correct": False}]},
        {"text": "Which vulnerability allows an attacker to make the server attack other servers?", "type": "multiple_choice", "topic": "SSRF", "difficulty": "Easy", "skill_focus": "Theory", "explanation": "SSRF makes the server a proxy for attacks.", "options": [{"text": "SSRF", "is_correct": True}, {"text": "XSS", "is_correct": False}, {"text": "CSRF", "is_correct": False}, {"text": "SQLi", "is_correct": False}]},
        {"text": "Can SSRF bypass local firewalls?", "type": "multiple_choice", "topic": "SSRF", "difficulty": "Medium", "skill_focus": "Theory", "explanation": "Yes, because the request originates from the trusted server inside the firewall.", "options": [{"text": "Yes, request is from trusted internal source", "is_correct": True}, {"text": "No, firewalls block everything", "is_correct": False}, {"text": "Only on Windows", "is_correct": False}, {"text": "Only on Linux", "is_correct": False}]},
        {"text": "What is 'DNS Rebinding' in the context of SSRF?", "type": "multiple_choice", "topic": "SSRF", "difficulty": "Hard", "skill_focus": "Exploitation", "explanation": "Changing DNS resolution from a safe IP to a malicious/internal IP during the check-time/use-time gap.", "options": [{"text": "Bypassing IP checks via DNS changes", "is_correct": True}, {"text": "Rebooting DNS server", "is_correct": False}, {"text": "Binding two DNS servers", "is_correct": False}, {"text": "Encrypting DNS", "is_correct": False}]},
    ])

    # --- 9. Ransomware ---
    questions.extend([
        {"text": "What does Ransomware do?", "type": "multiple_choice", "topic": "Ransomware", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "Encrypts files and demands payment.", "options": [{"text": "Encrypts files and demands payment", "is_correct": True}, {"text": "Deletes files silently", "is_correct": False}, {"text": "Steals internet bandwidth", "is_correct": False}, {"text": "Mines bitcoin only", "is_correct": False}]},
        {"text": "What is the best recovery method for Ransomware?", "type": "multiple_choice", "topic": "Ransomware", "difficulty": "Easy", "skill_focus": "Defense", "explanation": "Offline backups allow restoration without paying.", "options": [{"text": "Offline/Offline Backups", "is_correct": True}, {"text": "Paying the ransom", "is_correct": False}, {"text": "Restarting the PC", "is_correct": False}, {"text": "Calling the police", "is_correct": False}]},
        {"text": "What is 'Double Extortion' ransomware?", "type": "multiple_choice", "topic": "Ransomware", "difficulty": "Medium", "skill_focus": "Knowledge", "explanation": "Encrypting files AND threatening to leak stolen data.", "options": [{"text": "Encryption + Data Leak Threat", "is_correct": True}, {"text": "Asking for double money", "is_correct": False}, {"text": "Infecting two computers", "is_correct": False}, {"text": "Encrypting twice", "is_correct": False}]},
        {"text": "What cryptocurrency is most commonly requested in ransomware?", "type": "multiple_choice", "topic": "Ransomware", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "Bitcoin (or Monero) for anonymity.", "options": [{"text": "Bitcoin/Monero", "is_correct": True}, {"text": "Credit Card", "is_correct": False}, {"text": "Paypal", "is_correct": False}, {"text": "Bank Transfer", "is_correct": False}]},
        {"text": "WannaCry ransomware exploited which protocol?", "type": "multiple_choice", "topic": "Ransomware", "difficulty": "Medium", "skill_focus": "History", "explanation": "SMB (Server Message Block) via EternalBlue exploit.", "options": [{"text": "SMB (Server Message Block)", "is_correct": True}, {"text": "HTTP", "is_correct": False}, {"text": "FTP", "is_correct": False}, {"text": "SSH", "is_correct": False}]},
        {"text": "How is ransomware often delivered?", "type": "multiple_choice", "topic": "Ransomware", "difficulty": "Easy", "skill_focus": "Exploitation", "explanation": "Phishing emails are the top vector.", "options": [{"text": "Phishing Emails", "is_correct": True}, {"text": "Magic", "is_correct": False}, {"text": "Hardware failure", "is_correct": False}, {"text": "Power surge", "is_correct": False}]},
        {"text": "What is RaaS?", "type": "multiple_choice", "topic": "Ransomware", "difficulty": "Medium", "skill_focus": "Knowledge", "explanation": "Ransomware as a Service (affiliate model).", "options": [{"text": "Ransomware as a Service", "is_correct": True}, {"text": "Real and active Security", "is_correct": False}, {"text": "Root as a Service", "is_correct": False}, {"text": "Recovery as a Service", "is_correct": False}]},
        {"text": "Should you pay the ransom?", "type": "multiple_choice", "topic": "Ransomware", "difficulty": "Easy", "skill_focus": "Ethics/Policy", "explanation": "FBI advises no; it encourages attacks and doesn't guarantee data return.", "options": [{"text": "Generally No (No guarantee)", "is_correct": True}, {"text": "Yes, always", "is_correct": False}, {"text": "Only if it's cheap", "is_correct": False}, {"text": "Only on weekends", "is_correct": False}]},
        {"text": "What type of encryption does ransomware usually use?", "type": "multiple_choice", "topic": "Ransomware", "difficulty": "Hard", "skill_focus": "Crypto", "explanation": "Asymmetric (Public/Private key) so the victim can't decrypt without the private key held by attacker.", "options": [{"text": "Asymmetric (Public/Private Key)", "is_correct": True}, {"text": "ROT13", "is_correct": False}, {"text": "Base64", "is_correct": False}, {"text": "XOR", "is_correct": False}]},
        {"text": "What is a 'Kill Switch' in ransomware context?", "type": "multiple_choice", "topic": "Ransomware", "difficulty": "Medium", "skill_focus": "History", "explanation": "A mechanism (like a domain check) that stops the malware spreading (famous in WannaCry).", "options": [{"text": "Mechanism to stop execution", "is_correct": True}, {"text": "Button to delete PC", "is_correct": False}, {"text": "Deleting the virus", "is_correct": False}, {"text": "Turning off power", "is_correct": False}]},
    ])

    # --- 10. Buffer Overflow ---
    questions.extend([
        {"text": "What causes a Buffer Overflow?", "type": "multiple_choice", "topic": "Buffer Overflow", "difficulty": "Easy", "skill_focus": "Theory", "explanation": "Writing more data to a buffer than it can hold.", "options": [{"text": "Writing past memory boundaries", "is_correct": True}, {"text": "Hard drive full", "is_correct": False}, {"text": "Too many files", "is_correct": False}, {"text": "Slow CPU", "is_correct": False}]},
        {"text": "Which languages are most susceptible to Buffer Overflows?", "type": "multiple_choice", "topic": "Buffer Overflow", "difficulty": "Medium", "skill_focus": "Knowledge", "explanation": "C and C++ do not have built-in memory safety.", "options": [{"text": "C / C++", "is_correct": True}, {"text": "Python", "is_correct": False}, {"text": "Java", "is_correct": False}, {"text": "JavaScript", "is_correct": False}]},
        {"text": "What is the 'Stack' in memory?", "type": "multiple_choice", "topic": "Buffer Overflow", "difficulty": "Medium", "skill_focus": "Theory", "explanation": "Memory region for local variables and function control flow.", "options": [{"text": "Region for local variables/control flow", "is_correct": True}, {"text": "Long term storage", "is_correct": False}, {"text": "Hard drive space", "is_correct": False}, {"text": "Graphics memory", "is_correct": False}]},
        {"text": "What is the 'Heap'?", "type": "multiple_choice", "topic": "Buffer Overflow", "difficulty": "Medium", "skill_focus": "Theory", "explanation": "Dynamic memory allocation.", "options": [{"text": "Dynamic memory area", "is_correct": True}, {"text": "Static memory area", "is_correct": False}, {"text": "Code area", "is_correct": False}, {"text": "Kernel area", "is_correct": False}]},
        {"text": "What does a Buffer Overflow often allow an attacker to overwrite?", "type": "multiple_choice", "topic": "Buffer Overflow", "difficulty": "Hard", "skill_focus": "Exploitation", "explanation": "The Return Address (EIP/RIP) controls what code executes next.", "options": [{"text": "Return Address (EIP/RIP)", "is_correct": True}, {"text": "Screen resolution", "is_correct": False}, {"text": "Keyboard layout", "is_correct": False}, {"text": "Mouse speed", "is_correct": False}]},
        {"text": "What is 'Shellcode'?", "type": "multiple_choice", "topic": "Buffer Overflow", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "Small piece of code used as the payload (usually spawns a shell).", "options": [{"text": "Payload code to spawn a shell", "is_correct": True}, {"text": "Code to format drive", "is_correct": False}, {"text": "Code to change colors", "is_correct": False}, {"text": "Code to zip files", "is_correct": False}]},
        {"text": "What is ASLR?", "type": "multiple_choice", "topic": "Buffer Overflow", "difficulty": "Hard", "skill_focus": "Defense", "explanation": "Address Space Layout Randomization moves memory locations around.", "options": [{"text": "Address Space Layout Randomization", "is_correct": True}, {"text": "Anti-Shell Logic Rule", "is_correct": False}, {"text": "Advanced Security Level Rating", "is_correct": False}, {"text": "Auto System Lock Routine", "is_correct": False}]},
        {"text": "What is a Canary (Stack Cookie)?", "type": "multiple_choice", "topic": "Buffer Overflow", "difficulty": "Hard", "skill_focus": "Defense", "explanation": "A value placed on the stack to detect overflows before the return address is reached.", "options": [{"text": "Value to detect stack corruption", "is_correct": True}, {"text": "A bird", "is_correct": False}, {"text": "A password", "is_correct": False}, {"text": "A firewall rule", "is_correct": False}]},
        {"text": "What is a NOP Sled?", "type": "multiple_choice", "topic": "Buffer Overflow", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "Sequence of No-Operation instructions to slide execution into shellcode.", "options": [{"text": "Sequence of No-Operation instructions", "is_correct": True}, {"text": "A hacking tool", "is_correct": False}, {"text": "A password cracker", "is_correct": False}, {"text": "A network scanner", "is_correct": False}]},
        {"text": "What is DEP / NX?", "type": "multiple_choice", "topic": "Buffer Overflow", "difficulty": "Hard", "skill_focus": "Defense", "explanation": "Data Execution Prevention / No-Execute makes the stack non-executable.", "options": [{"text": "Prevents code execution in data segments", "is_correct": True}, {"text": "Prevents data deletion", "is_correct": False}, {"text": "Prevents encryption", "is_correct": False}, {"text": "Prevents networking", "is_correct": False}]},
    ])

    # --- 11. XXE (XML External Entity) ---
    questions.extend([
        {"text": "What does XXE stand for?", "type": "multiple_choice", "topic": "XXE", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "XML External Entity.", "options": [{"text": "XML External Entity", "is_correct": True}, {"text": "X-Ray External Entry", "is_correct": False}, {"text": "XML Extra Encryption", "is_correct": False}, {"text": "Xenon Extra Entry", "is_correct": False}]},
        {"text": "XXE attacks target applications that parse what format?", "type": "multiple_choice", "topic": "XXE", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "XML.", "options": [{"text": "XML", "is_correct": True}, {"text": "JSON", "is_correct": False}, {"text": "YAML", "is_correct": False}, {"text": "CSV", "is_correct": False}]},
        {"text": "What is a common impact of XXE?", "type": "multiple_choice", "topic": "XXE", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "Local File Disclosure (reading /etc/passwd).", "options": [{"text": "Reading local files", "is_correct": True}, {"text": "Formatting C drive", "is_correct": False}, {"text": "Changing CSS", "is_correct": False}, {"text": "Playing audio", "is_correct": False}]},
        {"text": "What entity definition is usually used in XXE?", "type": "multiple_choice", "topic": "XXE", "difficulty": "Hard", "skill_focus": "Exploitation", "explanation": "<!DOCTYPE foo [ <!ENTITY xxe SYSTEM 'file:///etc/passwd'> ]>", "options": [{"text": "SYSTEM entity", "is_correct": True}, {"text": "LOCAL entity", "is_correct": False}, {"text": "GLOBAL entity", "is_correct": False}, {"text": "PRIVATE entity", "is_correct": False}]},
        {"text": "How do you prevent XXE?", "type": "multiple_choice", "topic": "XXE", "difficulty": "Medium", "skill_focus": "Defense", "explanation": "Disable DTDs (Document Type Definitions) and external entities.", "options": [{"text": "Disable DTDs / External Entities", "is_correct": True}, {"text": "Use Firewall", "is_correct": False}, {"text": "Use HTTPS", "is_correct": False}, {"text": "Reboot Server", "is_correct": False}]},
        {"text": "Can XXE lead to SSRF?", "type": "multiple_choice", "topic": "XXE", "difficulty": "Medium", "skill_focus": "Theory", "explanation": "Yes, by making the XML parser fetch a URL.", "options": [{"text": "Yes", "is_correct": True}, {"text": "No", "is_correct": False}, {"text": "Only via Bluetooth", "is_correct": False}, {"text": "Only on Mac", "is_correct": False}]},
        {"text": "What is a 'Billion Laughs' attack?", "type": "multiple_choice", "topic": "XXE", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "XML Bomb (DoS) using recursive entity expansion.", "options": [{"text": "XML Bomb / DoS", "is_correct": True}, {"text": "Funny Virus", "is_correct": False}, {"text": "Audio attack", "is_correct": False}, {"text": "Video attack", "is_correct": False}]},
        {"text": "Is JSON vulnerable to XXE?", "type": "multiple_choice", "topic": "XXE", "difficulty": "Easy", "skill_focus": "Theory", "explanation": "No, JSON does not have entities like XML.", "options": [{"text": "No", "is_correct": True}, {"text": "Yes", "is_correct": False}, {"text": "Sometimes", "is_correct": False}, {"text": "If converted to XML", "is_correct": False}]},
        {"text": "What does DTD stand for?", "type": "multiple_choice", "topic": "XXE", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "Document Type Definition.", "options": [{"text": "Document Type Definition", "is_correct": True}, {"text": "Data Type Definition", "is_correct": False}, {"text": "Domain Transfer Data", "is_correct": False}, {"text": "Direct Text Data", "is_correct": False}]},
        {"text": "Which XML feature is the root cause of XXE?", "type": "multiple_choice", "topic": "XXE", "difficulty": "Medium", "skill_focus": "Theory", "explanation": "External entities.", "options": [{"text": "External Entities", "is_correct": True}, {"text": "Tags", "is_correct": False}, {"text": "Attributes", "is_correct": False}, {"text": "Comments", "is_correct": False}]},
    ])

    # --- 12. Directory / Path Traversal ---
    questions.extend([
        {"text": "What character sequence is used for Directory Traversal?", "type": "multiple_choice", "topic": "Path Traversal", "difficulty": "Easy", "skill_focus": "Exploitation", "explanation": "../ moves up a directory.", "options": [{"text": "../ (Dot Dot Slash)", "is_correct": True}, {"text": "||", "is_correct": False}, {"text": "&&", "is_correct": False}, {"text": "##", "is_correct": False}]},
        {"text": "What is the goal of Path Traversal?", "type": "multiple_choice", "topic": "Path Traversal", "difficulty": "Easy", "skill_focus": "Exploitation", "explanation": "Access files outside the web root.", "options": [{"text": "Access files outside web root", "is_correct": True}, {"text": "Delete files", "is_correct": False}, {"text": "Upload files", "is_correct": False}, {"text": "Execute files", "is_correct": False}]},
        {"text": "If you see 'image=../../etc/passwd', what attack is this?", "type": "multiple_choice", "topic": "Path Traversal", "difficulty": "Easy", "skill_focus": "Recognition", "explanation": "Path Traversal.", "options": [{"text": "Path Traversal", "is_correct": True}, {"text": "SQL Injection", "is_correct": False}, {"text": "XSS", "is_correct": False}, {"text": "CSRF", "is_correct": False}]},
        {"text": "How do you prevent Path Traversal?", "type": "multiple_choice", "topic": "Path Traversal", "difficulty": "Medium", "skill_focus": "Defense", "explanation": "Validate input against a whitelist of filenames and avoid direct file API access.", "options": [{"text": "Input validation and canonicalization", "is_correct": True}, {"text": "Disable images", "is_correct": False}, {"text": "Use CSS", "is_correct": False}, {"text": "Shorten URLs", "is_correct": False}]},
        {"text": "What is 'Canonicalization'?", "type": "multiple_choice", "topic": "Path Traversal", "difficulty": "Hard", "skill_focus": "Defense", "explanation": "Converting data to its simplest, standard form (resolving ../).", "options": [{"text": "Resolving paths to standard form", "is_correct": True}, {"text": "Zipping files", "is_correct": False}, {"text": "Encrypting files", "is_correct": False}, {"text": "Deleting logs", "is_correct": False}]},
        {"text": "What is the null byte (%00) trick used for?", "type": "multiple_choice", "topic": "Path Traversal", "difficulty": "Hard", "skill_focus": "Exploitation", "explanation": "In older systems (C-based), it terminates the string, bypassing extension checks (.php%00.jpg).", "options": [{"text": "Terminating strings early", "is_correct": True}, {"text": "Making files empty", "is_correct": False}, {"text": "Adding zero value", "is_correct": False}, {"text": "Nothing", "is_correct": False}]},
        {"text": "Can Path Traversal lead to Remote Code Execution?", "type": "multiple_choice", "topic": "Path Traversal", "difficulty": "Medium", "skill_focus": "Theory", "explanation": "Yes, if you can upload a file and then traverse to execute it, or read config files with passwords.", "options": [{"text": "Yes, in some scenarios", "is_correct": True}, {"text": "No, never", "is_correct": False}, {"text": "Only on Tuesdays", "is_correct": False}, {"text": "Only via Email", "is_correct": False}]},
        {"text": "What OS uses backslashes '\\' often causing traversal confusion?", "type": "multiple_choice", "topic": "Path Traversal", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "Windows.", "options": [{"text": "Windows", "is_correct": True}, {"text": "Linux", "is_correct": False}, {"text": "Mac", "is_correct": False}, {"text": "Android", "is_correct": False}]},
        {"text": "What is 'Dot Dot Pwn'?", "type": "multiple_choice", "topic": "Path Traversal", "difficulty": "Medium", "skill_focus": "Tools", "explanation": "A fuzzer for directory traversal.", "options": [{"text": "Traversal Fuzzer Tool", "is_correct": True}, {"text": "A game", "is_correct": False}, {"text": "A virus", "is_correct": False}, {"text": "A firewall", "is_correct": False}]},
        {"text": "Is chroot() a defense against traversal?", "type": "multiple_choice", "topic": "Path Traversal", "difficulty": "Medium", "skill_focus": "Defense", "explanation": "Yes, it jails the process to a specific directory.", "options": [{"text": "Yes, it jails the process", "is_correct": True}, {"text": "No", "is_correct": False}, {"text": "It makes it worse", "is_correct": False}, {"text": "Only for root users", "is_correct": False}]},
    ])

    # --- 13. Insecure Deserialization ---
    questions.extend([
        {"text": "What is Serialization?", "type": "multiple_choice", "topic": "Deserialization", "difficulty": "Easy", "skill_focus": "Theory", "explanation": "Converting an object into a data stream (e.g., JSON, XML, Binary).", "options": [{"text": "Converting object to data stream", "is_correct": True}, {"text": "Encrypting data", "is_correct": False}, {"text": "Deleting data", "is_correct": False}, {"text": "Sorting data", "is_correct": False}]},
        {"text": "What is Deserialization?", "type": "multiple_choice", "topic": "Deserialization", "difficulty": "Easy", "skill_focus": "Theory", "explanation": "Converting data stream back to an object.", "options": [{"text": "Converting stream back to object", "is_correct": True}, {"text": "Decrypting data", "is_correct": False}, {"text": "Creating data", "is_correct": False}, {"text": "Hiding data", "is_correct": False}]},
        {"text": "What is the danger of Insecure Deserialization?", "type": "multiple_choice", "topic": "Deserialization", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "Remote Code Execution (RCE) via object injection.", "options": [{"text": "Remote Code Execution (RCE)", "is_correct": True}, {"text": "CSS injection", "is_correct": False}, {"text": "Slow internet", "is_correct": False}, {"text": "Spam emails", "is_correct": False}]},
        {"text": "Which Java tool is famous for generating deserialization payloads?", "type": "multiple_choice", "topic": "Deserialization", "difficulty": "Hard", "skill_focus": "Tools", "explanation": "ysoserial.", "options": [{"text": "ysoserial", "is_correct": True}, {"text": "javahack", "is_correct": False}, {"text": "serialkiller", "is_correct": False}, {"text": "objectmapper", "is_correct": False}]},
        {"text": "In Python, which library is known for deserialization vulnerabilities?", "type": "multiple_choice", "topic": "Deserialization", "difficulty": "Medium", "skill_focus": "Knowledge", "explanation": "Pickle.", "options": [{"text": "Pickle", "is_correct": True}, {"text": "Pandas", "is_correct": False}, {"text": "NumPy", "is_correct": False}, {"text": "Requests", "is_correct": False}]},
        {"text": "What is a 'Gadget Chain'?", "type": "multiple_choice", "topic": "Deserialization", "difficulty": "Hard", "skill_focus": "Theory", "explanation": "A sequence of existing code snippets executed during deserialization to achieve RCE.", "options": [{"text": "Sequence of code chunks for RCE", "is_correct": True}, {"text": "A physical tool", "is_correct": False}, {"text": "A blockchain", "is_correct": False}, {"text": "A password list", "is_correct": False}]},
        {"text": "How do you prevent Deserialization attacks?", "type": "multiple_choice", "topic": "Deserialization", "difficulty": "Medium", "skill_focus": "Defense", "explanation": "Don't deserialize untrusted data; use simple formats like JSON without logic.", "options": [{"text": "Avoid deserializing untrusted data", "is_correct": True}, {"text": "Use shorter variables", "is_correct": False}, {"text": "Use more memory", "is_correct": False}, {"text": "Restart often", "is_correct": False}]},
        {"text": "Is PHP `unserialize()` vulnerable?", "type": "multiple_choice", "topic": "Deserialization", "difficulty": "Medium", "skill_focus": "Knowledge", "explanation": "Yes, if input is user-controlled.", "options": [{"text": "Yes", "is_correct": True}, {"text": "No", "is_correct": False}, {"text": "Only in PHP 4", "is_correct": False}, {"text": "Only on Linux", "is_correct": False}]},
        {"text": "What magic method in PHP is often a target?", "type": "multiple_choice", "topic": "Deserialization", "difficulty": "Hard", "skill_focus": "Knowledge", "explanation": "__destruct() or __wakeup().", "options": [{"text": "__destruct()", "is_correct": True}, {"text": "__init()", "is_correct": False}, {"text": "__main()", "is_correct": False}, {"text": "__print()", "is_correct": False}]},
        {"text": "Are cookies a vector for deserialization attacks?", "type": "multiple_choice", "topic": "Deserialization", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "Yes, if the cookie contains a serialized object.", "options": [{"text": "Yes", "is_correct": True}, {"text": "No", "is_correct": False}, {"text": "Only session IDs", "is_correct": False}, {"text": "Cookies are text only", "is_correct": False}]},
    ])

    # --- 14. Session Hijacking ---
    questions.extend([
        {"text": "What is Session Hijacking?", "type": "multiple_choice", "topic": "Session Hijacking", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "Taking over a user's active session.", "options": [{"text": "Taking over active session", "is_correct": True}, {"text": "Stealing a laptop", "is_correct": False}, {"text": "Crashing the server", "is_correct": False}, {"text": "Phishing password", "is_correct": False}]},
        {"text": "What is the most common token used to track sessions?", "type": "multiple_choice", "topic": "Session Hijacking", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "Session ID (Cookie).", "options": [{"text": "Session ID Cookie", "is_correct": True}, {"text": "IP Address", "is_correct": False}, {"text": "MAC Address", "is_correct": False}, {"text": "Username", "is_correct": False}]},
        {"text": "What is 'Session Fixation'?", "type": "multiple_choice", "topic": "Session Hijacking", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "Attacker sets the user's session ID before they log in.", "options": [{"text": "Attacker sets Session ID beforehand", "is_correct": True}, {"text": "Fixing broken sessions", "is_correct": False}, {"text": "Deleting sessions", "is_correct": False}, {"text": "Locking sessions", "is_correct": False}]},
        {"text": "What defense prevents Session Hijacking via XSS?", "type": "multiple_choice", "topic": "Session Hijacking", "difficulty": "Medium", "skill_focus": "Defense", "explanation": "HttpOnly flag prevents JS reading cookies.", "options": [{"text": "HttpOnly flag", "is_correct": True}, {"text": "CSS", "is_correct": False}, {"text": "HTML5", "is_correct": False}, {"text": "Flash", "is_correct": False}]},
        {"text": "What should happen to the Session ID after login?", "type": "multiple_choice", "topic": "Session Hijacking", "difficulty": "Medium", "skill_focus": "Defense", "explanation": "It should be regenerated to prevent Fixation.", "options": [{"text": "Regenerated", "is_correct": True}, {"text": "Kept same", "is_correct": False}, {"text": "Deleted", "is_correct": False}, {"text": "Printed", "is_correct": False}]},
        {"text": "Predictable Session IDs allow what?", "type": "multiple_choice", "topic": "Session Hijacking", "difficulty": "Easy", "skill_focus": "Exploitation", "explanation": "Guessing valid sessions of other users.", "options": [{"text": "Guessing other users' sessions", "is_correct": True}, {"text": "Faster login", "is_correct": False}, {"text": "Better UI", "is_correct": False}, {"text": "Less bandwidth", "is_correct": False}]},
        {"text": "What protocol protects Session IDs in transit?", "type": "multiple_choice", "topic": "Session Hijacking", "difficulty": "Easy", "skill_focus": "Defense", "explanation": "TLS (HTTPS).", "options": [{"text": "TLS/HTTPS", "is_correct": True}, {"text": "HTTP", "is_correct": False}, {"text": "FTP", "is_correct": False}, {"text": "Telnet", "is_correct": False}]},
        {"text": "What is 'Session Side-Jacking'?", "type": "multiple_choice", "topic": "Session Hijacking", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "Sniffing unencrypted cookies on Wi-Fi.", "options": [{"text": "Sniffing cookies on Wi-Fi", "is_correct": True}, {"text": "Stealing laptops", "is_correct": False}, {"text": "Breaking into servers", "is_correct": False}, {"text": "Phishing", "is_correct": False}]},
        {"text": "How long should a session timeout be?", "type": "multiple_choice", "topic": "Session Hijacking", "difficulty": "Easy", "skill_focus": "Defense", "explanation": "Short enough to minimize risk, long enough for usability.", "options": [{"text": "Short (e.g., 15-30 mins inactivity)", "is_correct": True}, {"text": "Infinite", "is_correct": False}, {"text": "1 year", "is_correct": False}, {"text": "1 second", "is_correct": False}]},
        {"text": "Can JWTs (JSON Web Tokens) be hijacked?", "type": "multiple_choice", "topic": "Session Hijacking", "difficulty": "Medium", "skill_focus": "Theory", "explanation": "Yes, if the token is stolen, it can be used until expiry.", "options": [{"text": "Yes, they are bearer tokens", "is_correct": True}, {"text": "No, they are secure", "is_correct": False}, {"text": "Only if signed", "is_correct": False}, {"text": "Only if encrypted", "is_correct": False}]},
    ])

    # --- 15. Command Injection ---
    questions.extend([
        {"text": "What is OS Command Injection?", "type": "multiple_choice", "topic": "Command Injection", "difficulty": "Easy", "skill_focus": "Theory", "explanation": "Executing system commands on the server via input.", "options": [{"text": "Executing system commands via input", "is_correct": True}, {"text": "Injecting SQL", "is_correct": False}, {"text": "Injecting CSS", "is_correct": False}, {"text": "Opening a command prompt on client", "is_correct": False}]},
        {"text": "Which character separates commands in Linux (e.g., cat file; ls)?", "type": "multiple_choice", "topic": "Command Injection", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "; (Semicolon) allows chaining commands.", "options": [{"text": "; (Semicolon)", "is_correct": True}, {"text": ": (Colon)", "is_correct": False}, {"text": ". (Dot)", "is_correct": False}, {"text": "_ (Underscore)", "is_correct": False}]},
        {"text": "What does the pipe operator '|' do?", "type": "multiple_choice", "topic": "Command Injection", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "Passes output of one command to another.", "options": [{"text": "Pipes output to next command", "is_correct": True}, {"text": "Stops command", "is_correct": False}, {"text": "Deletes command", "is_correct": False}, {"text": "Nothing", "is_correct": False}]},
        {"text": "In Python, which function is dangerous if inputs aren't sanitized?", "type": "multiple_choice", "topic": "Command Injection", "difficulty": "Medium", "skill_focus": "Knowledge", "explanation": "os.system() or subprocess.call(shell=True).", "options": [{"text": "os.system()", "is_correct": True}, {"text": "print()", "is_correct": False}, {"text": "len()", "is_correct": False}, {"text": "math.sqrt()", "is_correct": False}]},
        {"text": "What is the best defense against Command Injection?", "type": "multiple_choice", "topic": "Command Injection", "difficulty": "Medium", "skill_focus": "Defense", "explanation": "Avoid calling system commands; use language APIs.", "options": [{"text": "Use API libraries instead of shell commands", "is_correct": True}, {"text": "Use Firewalls", "is_correct": False}, {"text": "Use Antivirus", "is_correct": False}, {"text": "Hide the code", "is_correct": False}]},
        {"text": "What command helps check current user identity?", "type": "multiple_choice", "topic": "Command Injection", "difficulty": "Easy", "skill_focus": "Exploitation", "explanation": "whoami", "options": [{"text": "whoami", "is_correct": True}, {"text": "whereami", "is_correct": False}, {"text": "whatisthis", "is_correct": False}, {"text": "hello", "is_correct": False}]},
        {"text": "What is 'Blind' Command Injection?", "type": "multiple_choice", "topic": "Command Injection", "difficulty": "Hard", "skill_focus": "Theory", "explanation": "No output is returned; attacker uses time delays (ping/sleep).", "options": [{"text": "No output returned, uses time delays", "is_correct": True}, {"text": "Output is encrypted", "is_correct": False}, {"text": "Screen turns black", "is_correct": False}, {"text": "Keyboard stops working", "is_correct": False}]},
        {"text": "Which character represents a variable in bash?", "type": "multiple_choice", "topic": "Command Injection", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "$", "options": [{"text": "$", "is_correct": True}, {"text": "#", "is_correct": False}, {"text": "%", "is_correct": False}, {"text": "&", "is_correct": False}]},
        {"text": "Why is '&&' dangerous in inputs?", "type": "multiple_choice", "topic": "Command Injection", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "It executes the second command if the first succeeds.", "options": [{"text": "Executes next command if previous succeeds", "is_correct": True}, {"text": "It means AND logic", "is_correct": False}, {"text": "It comments out code", "is_correct": False}, {"text": "It escapes characters", "is_correct": False}]},
        {"text": "Does 'escapeshellarg()' in PHP make it safe?", "type": "multiple_choice", "topic": "Command Injection", "difficulty": "Hard", "skill_focus": "Defense", "explanation": "It helps by adding quotes, but avoiding shell execution is better.", "options": [{"text": "It adds quotes to make it safer", "is_correct": True}, {"text": "It executes the command", "is_correct": False}, {"text": "It deletes the command", "is_correct": False}, {"text": "It does nothing", "is_correct": False}]},
    ])

    # --- 16. Zero-Day Exploits ---
    questions.extend([
        {"text": "What is a Zero-Day vulnerability?", "type": "multiple_choice", "topic": "Zero-Day", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "A vulnerability known to attackers but not the vendor (0 days to patch).", "options": [{"text": "Unknown to vendor, no patch exists", "is_correct": True}, {"text": "A virus that lasts 0 days", "is_correct": False}, {"text": "Old vulnerability", "is_correct": False}, {"text": "Fake vulnerability", "is_correct": False}]},
        {"text": "What is a Zero-Day Exploit?", "type": "multiple_choice", "topic": "Zero-Day", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "Code that takes advantage of a Zero-Day vulnerability.", "options": [{"text": "Code attacking a Zero-Day", "is_correct": True}, {"text": "A patch", "is_correct": False}, {"text": "A scanner", "is_correct": False}, {"text": "A firewall", "is_correct": False}]},
        {"text": "Who typically buys Zero-Days?", "type": "multiple_choice", "topic": "Zero-Day", "difficulty": "Medium", "skill_focus": "Context", "explanation": "Governments, criminals, and security brokers (like Zerodium).", "options": [{"text": "Governments / Criminals / Brokers", "is_correct": True}, {"text": "Regular users", "is_correct": False}, {"text": "Students", "is_correct": False}, {"text": "Libraries", "is_correct": False}]},
        {"text": "What is 'Responsible Disclosure'?", "type": "multiple_choice", "topic": "Zero-Day", "difficulty": "Medium", "skill_focus": "Ethics", "explanation": "Telling the vendor privately so they can patch it before public release.", "options": [{"text": "Reporting to vendor privately first", "is_correct": True}, {"text": "Posting on Twitter immediately", "is_correct": False}, {"text": "Selling it on Dark Web", "is_correct": False}, {"text": "Keeping it secret forever", "is_correct": False}]},
        {"text": "What is a Bug Bounty Program?", "type": "multiple_choice", "topic": "Zero-Day", "difficulty": "Easy", "skill_focus": "Context", "explanation": "Companies paying hackers for reporting bugs.", "options": [{"text": "Paying for reported bugs", "is_correct": True}, {"text": "Hunting insects", "is_correct": False}, {"text": "Buying software", "is_correct": False}, {"text": "Hiring support", "is_correct": False}]},
        {"text": "Stuxnet used how many Zero-Days?", "type": "multiple_choice", "topic": "Zero-Day", "difficulty": "Hard", "skill_focus": "History", "explanation": "Stuxnet famously used 4 Zero-Days.", "options": [{"text": "4", "is_correct": True}, {"text": "1", "is_correct": False}, {"text": "0", "is_correct": False}, {"text": "100", "is_correct": False}]},
        {"text": "How do you defend against Zero-Days?", "type": "multiple_choice", "topic": "Zero-Day", "difficulty": "Medium", "skill_focus": "Defense", "explanation": "Defense in Depth (layering security) since you can't patch what you don't know.", "options": [{"text": "Defense in Depth / Behavioral Analysis", "is_correct": True}, {"text": "Update windows", "is_correct": False}, {"text": "Use weak passwords", "is_correct": False}, {"text": "Turn off internet", "is_correct": False}]},
        {"text": "What is 'Heuristic Analysis'?", "type": "multiple_choice", "topic": "Zero-Day", "difficulty": "Hard", "skill_focus": "Defense", "explanation": "Detecting malware by behavior/patterns rather than signatures.", "options": [{"text": "Detecting by behavior/patterns", "is_correct": True}, {"text": "Detecting by exact match", "is_correct": False}, {"text": "Manual reading", "is_correct": False}, {"text": "Guessing", "is_correct": False}]},
        {"text": "What does CVE stand for?", "type": "multiple_choice", "topic": "Zero-Day", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "Common Vulnerabilities and Exposures.", "options": [{"text": "Common Vulnerabilities and Exposures", "is_correct": True}, {"text": "Computer Virus Entry", "is_correct": False}, {"text": "Critical Value Error", "is_correct": False}, {"text": "Central Virus Engine", "is_correct": False}]},
        {"text": "Once a patch is released, is it still a Zero-Day?", "type": "multiple_choice", "topic": "Zero-Day", "difficulty": "Easy", "skill_focus": "Theory", "explanation": "No, it becomes a known vulnerability (N-Day).", "options": [{"text": "No", "is_correct": True}, {"text": "Yes", "is_correct": False}, {"text": "Forever", "is_correct": False}, {"text": "Maybe", "is_correct": False}]},
    ])

    # --- 17. DNS Spoofing / Poisoning ---
    questions.extend([
        {"text": "What is DNS Cache Poisoning?", "type": "multiple_choice", "topic": "DNS Spoofing", "difficulty": "Medium", "skill_focus": "Theory", "explanation": "Injecting fake records into a DNS resolver's cache.", "options": [{"text": "Injecting fake records into cache", "is_correct": True}, {"text": "Deleting DNS server", "is_correct": False}, {"text": "Stealing DNS server", "is_correct": False}, {"text": "Encrypting DNS", "is_correct": False}]},
        {"text": "What is the result of DNS Spoofing?", "type": "multiple_choice", "topic": "DNS Spoofing", "difficulty": "Easy", "skill_focus": "Exploitation", "explanation": "Users typing 'google.com' go to a malicious site.", "options": [{"text": "Redirecting users to wrong sites", "is_correct": True}, {"text": "Faster internet", "is_correct": False}, {"text": "Free internet", "is_correct": False}, {"text": "Blue screen", "is_correct": False}]},
        {"text": "What security extension prevents DNS Spoofing?", "type": "multiple_choice", "topic": "DNS Spoofing", "difficulty": "Medium", "skill_focus": "Defense", "explanation": "DNSSEC signs records cryptographically.", "options": [{"text": "DNSSEC", "is_correct": True}, {"text": "HTTPS", "is_correct": False}, {"text": "SSL", "is_correct": False}, {"text": "WEP", "is_correct": False}]},
        {"text": "What file on a local computer overrides DNS?", "type": "multiple_choice", "topic": "DNS Spoofing", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "The 'hosts' file.", "options": [{"text": "hosts file", "is_correct": True}, {"text": "config.sys", "is_correct": False}, {"text": "registry", "is_correct": False}, {"text": "autoexec.bat", "is_correct": False}]},
        {"text": "What is 'Pharming'?", "type": "multiple_choice", "topic": "DNS Spoofing", "difficulty": "Medium", "skill_focus": "Knowledge", "explanation": "Redirecting traffic to a fake site via DNS poisoning (without user clicking links).", "options": [{"text": "Redirecting traffic via DNS manipulation", "is_correct": True}, {"text": "Farming gold", "is_correct": False}, {"text": "Planting viruses", "is_correct": False}, {"text": "Harvesting emails", "is_correct": False}]},
        {"text": "What UDP port does DNS use?", "type": "multiple_choice", "topic": "DNS Spoofing", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "53.", "options": [{"text": "53", "is_correct": True}, {"text": "80", "is_correct": False}, {"text": "443", "is_correct": False}, {"text": "21", "is_correct": False}]},
        {"text": "Why is UDP used for DNS (making it easier to spoof)?", "type": "multiple_choice", "topic": "DNS Spoofing", "difficulty": "Medium", "skill_focus": "Theory", "explanation": "UDP is connectionless and faster, but easier to forge packets.", "options": [{"text": "Connectionless / Faster", "is_correct": True}, {"text": "More secure", "is_correct": False}, {"text": "Encrypted", "is_correct": False}, {"text": "Newer", "is_correct": False}]},
        {"text": "What is the Kaminsky Vulnerability?", "type": "multiple_choice", "topic": "DNS Spoofing", "difficulty": "Hard", "skill_focus": "History", "explanation": "A famous flaw allowing reliable DNS cache poisoning via transaction ID guessing.", "options": [{"text": "Flaw allowing reliable cache poisoning", "is_correct": True}, {"text": "A virus", "is_correct": False}, {"text": "A firewall hole", "is_correct": False}, {"text": "A browser bug", "is_correct": False}]},
        {"text": "DoVPNs help against local DNS Spoofing?", "type": "multiple_choice", "topic": "DNS Spoofing", "difficulty": "Medium", "skill_focus": "Defense", "explanation": "Yes, they encrypt traffic to a trusted DNS server, bypassing local spoofing.", "options": [{"text": "Yes", "is_correct": True}, {"text": "No", "is_correct": False}, {"text": "Makes it worse", "is_correct": False}, {"text": "Only in China", "is_correct": False}]},
        {"text": "What is DNS over HTTPS (DoH)?", "type": "multiple_choice", "topic": "DNS Spoofing", "difficulty": "Medium", "skill_focus": "Defense", "explanation": "Encrypting DNS queries inside HTTPS traffic.", "options": [{"text": "Encrypted DNS via HTTPS", "is_correct": True}, {"text": "Websites over DNS", "is_correct": False}, {"text": "Fast DNS", "is_correct": False}, {"text": "Illegal DNS", "is_correct": False}]},
    ])

    # --- 18. Trojan Horses ---
    questions.extend([
        {"text": "What is a Trojan Horse?", "type": "multiple_choice", "topic": "Trojan Horse", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "Malware disguised as legitimate software.", "options": [{"text": "Malware disguised as legitimate software", "is_correct": True}, {"text": "Self-replicating worm", "is_correct": False}, {"text": "A wooden horse", "is_correct": False}, {"text": "A hardware bug", "is_correct": False}]},
        {"text": "Do Trojans self-replicate like worms?", "type": "multiple_choice", "topic": "Trojan Horse", "difficulty": "Medium", "skill_focus": "Theory", "explanation": "No, they require user interaction (execution) to spread.", "options": [{"text": "No", "is_correct": True}, {"text": "Yes", "is_correct": False}, {"text": "Sometimes", "is_correct": False}, {"text": "Only on Sundays", "is_correct": False}]},
        {"text": "What is a Remote Access Trojan (RAT)?", "type": "multiple_choice", "topic": "Trojan Horse", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "Gives attacker full remote control of the victim PC.", "options": [{"text": "Gives attacker remote control", "is_correct": True}, {"text": "A mouse virus", "is_correct": False}, {"text": "A screen recorder", "is_correct": False}, {"text": "A fast trojan", "is_correct": False}]},
        {"text": "How are Trojans usually delivered?", "type": "multiple_choice", "topic": "Trojan Horse", "difficulty": "Easy", "skill_focus": "Exploitation", "explanation": "Via downloaded games, cracks, or email attachments.", "options": [{"text": "Downloads / Email Attachments", "is_correct": True}, {"text": "Magic", "is_correct": False}, {"text": "Power cables", "is_correct": False}, {"text": "Monitor screen", "is_correct": False}]},
        {"text": "What is a 'Backdoor'?", "type": "multiple_choice", "topic": "Trojan Horse", "difficulty": "Easy", "skill_focus": "Theory", "explanation": "A hidden method for bypassing authentication to access a system.", "options": [{"text": "Hidden entry point", "is_correct": True}, {"text": "Rear door of a building", "is_correct": False}, {"text": "A firewall", "is_correct": False}, {"text": "A password", "is_correct": False}]},
        {"text": "What is a 'Logic Bomb'?", "type": "multiple_choice", "topic": "Trojan Horse", "difficulty": "Medium", "skill_focus": "Theory", "explanation": "Malicious code that executes only when specific conditions are met (time, date).", "options": [{"text": "Executes under specific conditions", "is_correct": True}, {"text": "An explosive", "is_correct": False}, {"text": "A math problem", "is_correct": False}, {"text": "A logical error", "is_correct": False}]},
        {"text": "What is Emotet?", "type": "multiple_choice", "topic": "Trojan Horse", "difficulty": "Medium", "skill_focus": "History", "explanation": "A famous banking Trojan that evolved into a malware distributor.", "options": [{"text": "Famous Banking Trojan / Loader", "is_correct": True}, {"text": "An emotion", "is_correct": False}, {"text": "A game", "is_correct": False}, {"text": "An antivirus", "is_correct": False}]},
        {"text": "Can a Trojan be inside a PDF?", "type": "multiple_choice", "topic": "Trojan Horse", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "Yes, exploits in the PDF reader can drop malware.", "options": [{"text": "Yes", "is_correct": True}, {"text": "No", "is_correct": False}, {"text": "Only TXT files", "is_correct": False}, {"text": "Only MP3s", "is_correct": False}]},
        {"text": "What is 'Binding' in the context of Trojans?", "type": "multiple_choice", "topic": "Trojan Horse", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "Merging a malicious file with a legitimate one (e.g., calc.exe + trojan).", "options": [{"text": "Merging malicious file with legitimate one", "is_correct": True}, {"text": "Tying knots", "is_correct": False}, {"text": "Compiling code", "is_correct": False}, {"text": "Zipping files", "is_correct": False}]},
        {"text": "What tool detects Trojans?", "type": "multiple_choice", "topic": "Trojan Horse", "difficulty": "Easy", "skill_focus": "Defense", "explanation": "Antivirus / Antimalware.", "options": [{"text": "Antivirus", "is_correct": True}, {"text": "Calculator", "is_correct": False}, {"text": "Paint", "is_correct": False}, {"text": "Notepad", "is_correct": False}]},
    ])

    # --- 19. Keylogging ---
    questions.extend([
        {"text": "What does a Keylogger do?", "type": "multiple_choice", "topic": "Keylogging", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "Records every keystroke made by the user.", "options": [{"text": "Records keystrokes", "is_correct": True}, {"text": "Locks keys", "is_correct": False}, {"text": "Makes keys louder", "is_correct": False}, {"text": "Types for you", "is_correct": False}]},
        {"text": "Can Keyloggers be Hardware-based?", "type": "multiple_choice", "topic": "Keylogging", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "Yes, physical devices plugged between keyboard and PC.", "options": [{"text": "Yes", "is_correct": True}, {"text": "No", "is_correct": False}, {"text": "Only on Mac", "is_correct": False}, {"text": "Only on Linux", "is_correct": False}]},
        {"text": "What is a 'Virtual Keyboard' used for?", "type": "multiple_choice", "topic": "Keylogging", "difficulty": "Medium", "skill_focus": "Defense", "explanation": "Clicking letters on screen bypasses hardware keyloggers (and some software ones).", "options": [{"text": "Bypassing keyloggers", "is_correct": True}, {"text": "Typing faster", "is_correct": False}, {"text": "Looking cool", "is_correct": False}, {"text": "Saving power", "is_correct": False}]},
        {"text": "What is 'Spyware'?", "type": "multiple_choice", "topic": "Keylogging", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "Software that secretly gathers information about a person.", "options": [{"text": "Software gathering info secretly", "is_correct": True}, {"text": "James Bond movie", "is_correct": False}, {"text": "Antivirus", "is_correct": False}, {"text": "A game", "is_correct": False}]},
        {"text": "Can a keylogger steal copied text (Clipboard)?", "type": "multiple_choice", "topic": "Keylogging", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "Yes, advanced loggers monitor clipboard data too.", "options": [{"text": "Yes", "is_correct": True}, {"text": "No", "is_correct": False}, {"text": "Only if you paste twice", "is_correct": False}, {"text": "Only images", "is_correct": False}]},
        {"text": "How do you detect a Hardware Keylogger?", "type": "multiple_choice", "topic": "Keylogging", "difficulty": "Medium", "skill_focus": "Defense", "explanation": "Physical inspection of the computer ports.", "options": [{"text": "Physical inspection", "is_correct": True}, {"text": "Antivirus software", "is_correct": False}, {"text": "Firewall", "is_correct": False}, {"text": "Restarting PC", "is_correct": False}]},
        {"text": "What is 'Stalkerware'?", "type": "multiple_choice", "topic": "Keylogging", "difficulty": "Medium", "skill_focus": "Context", "explanation": "Spyware used in domestic abuse scenarios to track partners.", "options": [{"text": "Spyware used to track partners/spouses", "is_correct": True}, {"text": "Tracking animals", "is_correct": False}, {"text": "Tracking satellites", "is_correct": False}, {"text": "Tracking packages", "is_correct": False}]},
        {"text": "Does encryption help against Keyloggers?", "type": "multiple_choice", "topic": "Keylogging", "difficulty": "Medium", "skill_focus": "Theory", "explanation": "No, because the keylogger captures the input *before* it is encrypted.", "options": [{"text": "No, input is captured before encryption", "is_correct": True}, {"text": "Yes, always", "is_correct": False}, {"text": "Only AES", "is_correct": False}, {"text": "Only RSA", "is_correct": False}]},
        {"text": "What is 'Form Grabbing'?", "type": "multiple_choice", "topic": "Keylogging", "difficulty": "Hard", "skill_focus": "Exploitation", "explanation": "Stealing data from web forms upon submission (often used by banking trojans).", "options": [{"text": "Stealing web form data", "is_correct": True}, {"text": "Grabbing a window", "is_correct": False}, {"text": "Moving forms", "is_correct": False}, {"text": "Creating forms", "is_correct": False}]},
        {"text": "Is a keylogger always malware?", "type": "multiple_choice", "topic": "Keylogging", "difficulty": "Easy", "skill_focus": "Context", "explanation": "No, they can be used for parental control or employee monitoring (legally grey/dependent on consent).", "options": [{"text": "No, used for monitoring too", "is_correct": True}, {"text": "Yes, always illegal", "is_correct": False}, {"text": "Only in Russia", "is_correct": False}, {"text": "Only in USA", "is_correct": False}]},
    ])

    # --- 20. Privilege Escalation ---
    questions.extend([
        {"text": "What is Privilege Escalation?", "type": "multiple_choice", "topic": "Privilege Escalation", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "Gaining higher permissions than initially granted.", "options": [{"text": "Gaining higher permissions", "is_correct": True}, {"text": "Going up an elevator", "is_correct": False}, {"text": "Downloading files", "is_correct": False}, {"text": "Installing software", "is_correct": False}]},
        {"text": "What is Vertical Privilege Escalation?", "type": "multiple_choice", "topic": "Privilege Escalation", "difficulty": "Medium", "skill_focus": "Theory", "explanation": "User -> Admin (Moving up).", "options": [{"text": "User to Admin", "is_correct": True}, {"text": "User to User", "is_correct": False}, {"text": "Admin to User", "is_correct": False}, {"text": "Admin to Root", "is_correct": False}]},
        {"text": "What is Horizontal Privilege Escalation?", "type": "multiple_choice", "topic": "Privilege Escalation", "difficulty": "Medium", "skill_focus": "Theory", "explanation": "User A -> User B (Same level, different account).", "options": [{"text": "User A to User B", "is_correct": True}, {"text": "User to Admin", "is_correct": False}, {"text": "Admin to Root", "is_correct": False}, {"text": "Guest to User", "is_correct": False}]},
        {"text": "What Linux command is often targeted for escalation (SUID)?", "type": "multiple_choice", "topic": "Privilege Escalation", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "Commands with SUID bit run as owner (root).", "options": [{"text": "SUID binaries", "is_correct": True}, {"text": "ls", "is_correct": False}, {"text": "cd", "is_correct": False}, {"text": "echo", "is_correct": False}]},
        {"text": "What is 'Dirty COW'?", "type": "multiple_choice", "topic": "Privilege Escalation", "difficulty": "Hard", "skill_focus": "History", "explanation": "A famous Linux kernel vulnerability (Copy-On-Write) for root escalation.", "options": [{"text": "Linux Kernel Exploit", "is_correct": True}, {"text": "A farm game", "is_correct": False}, {"text": "Windows Virus", "is_correct": False}, {"text": "Mac App", "is_correct": False}]},
        {"text": "What Windows file contains password hashes (SAM)?", "type": "multiple_choice", "topic": "Privilege Escalation", "difficulty": "Medium", "skill_focus": "Knowledge", "explanation": "SAM (Security Account Manager).", "options": [{"text": "SAM", "is_correct": True}, {"text": "PASS.TXT", "is_correct": False}, {"text": "WIN.INI", "is_correct": False}, {"text": "BOOT.INI", "is_correct": False}]},
        {"text": "What is 'UAC Bypass'?", "type": "multiple_choice", "topic": "Privilege Escalation", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "Bypassing Windows User Account Control prompts.", "options": [{"text": "Bypassing Windows UAC", "is_correct": True}, {"text": "Unlocking A Car", "is_correct": False}, {"text": "Using A Computer", "is_correct": False}, {"text": "Under A Cloud", "is_correct": False}]},
        {"text": "What is a 'Kernel Exploit' usually used for?", "type": "multiple_choice", "topic": "Privilege Escalation", "difficulty": "Hard", "skill_focus": "Exploitation", "explanation": "Gaining Root/System privileges.", "options": [{"text": "Gaining Root/System privileges", "is_correct": True}, {"text": "Crashing the browser", "is_correct": False}, {"text": "Playing music", "is_correct": False}, {"text": "Sending email", "is_correct": False}]},
        {"text": "Why are misconfigured Cron jobs (Linux) dangerous?", "type": "multiple_choice", "topic": "Privilege Escalation", "difficulty": "Medium", "skill_focus": "Exploitation", "explanation": "If a writable script runs as root, a user can modify it to become root.", "options": [{"text": "User can modify root scripts", "is_correct": True}, {"text": "They slow down PC", "is_correct": False}, {"text": "They consume disk space", "is_correct": False}, {"text": "They send spam", "is_correct": False}]},
        {"text": "What does 'sudo' stand for?", "type": "multiple_choice", "topic": "Privilege Escalation", "difficulty": "Easy", "skill_focus": "Knowledge", "explanation": "SuperUser DO.", "options": [{"text": "SuperUser DO", "is_correct": True}, {"text": "Super User Don't", "is_correct": False}, {"text": "System Undo Do", "is_correct": False}, {"text": "Simple User Do", "is_correct": False}]},
    ])

    return questions

def seed_data():
    wait_for_db()
    
    # --- CRITICAL FIX: CREATE TABLES BEFORE SEEDING ---
    logger.info("Ensuring database tables exist...")
    models.Base.metadata.create_all(bind=engine)
    # --------------------------------------------------

    db: Session = SessionLocal()
    try:
        # 1. Seed Users (Admin/Instructor)
        seed_users(db)

        # 2. Seed Questions
        existing_count = db.query(models.Question).count()
        if existing_count >= 200:
            logger.info(f"Database already has {existing_count} questions. Skipping seeding.")
            return

        logger.info(f"Database has {existing_count} questions. Seeding to reach 200...")

        # Get the massive list of 200 questions
        questions_data = generate_questions()

        count_added = 0
        for q_data in questions_data:
            # Check for duplicates to avoid constraint errors
            exists = db.query(models.Question).filter(models.Question.text == q_data["text"]).first()
            if exists:
                continue
                
            options_data = q_data.pop("options")
            question = models.Question(**q_data)
            db.add(question)
            db.commit()
            db.refresh(question)
            
            for opt_data in options_data:
                option = models.QuestionOption(**opt_data, question_id=question.id)
                db.add(option)
            db.commit()
            count_added += 1
            
        logger.info(f"Successfully seeded {count_added} new questions.")
        
    except Exception as e:
        logger.error(f"Error seeding database: {e}")
        db.rollback()
    finally:
        db.close()

if __name__ == "__main__":
    seed_data()